run:
  fields:
    dry_run:
      example: true
      default: false
      selector:
        boolean:
    overwrite:
      example: false
      default: false
      selector:
        boolean:
    entities:
      example: "light.kitchen"
      selector:
        entity:
          multiple: true

cleanup:
  fields:
    dry_run:
      example: true
      default: false
      selector:
        boolean:

assign_areas:
  fields:
    dry_run:
      example: true
      default: false
      selector:
        boolean:

assign_icons:
  fields:
    dry_run:
      example: true
      default: false
      selector:
        boolean:

remove_all:
  fields:
    dry_run:
      example: true
      default: false
      selector:
        boolean:

preview:
  fields: {}
